//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrizerieWebClient.FrizerieRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelProgramare", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ModelProgramare : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientField;
        
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipTunsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TipTuns {
            get {
                return this.TipTunsField;
            }
            set {
                if ((object.ReferenceEquals(this.TipTunsField, value) != true)) {
                    this.TipTunsField = value;
                    this.RaisePropertyChanged("TipTuns");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FrizerieRef.ProgramariServiceSoap")]
    public interface ProgramariServiceSoap {
        
        // CODEGEN: Generating message contract since element name client from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugaInDB", ReplyAction="*")]
        FrizerieWebClient.FrizerieRef.AdaugaInDBResponse AdaugaInDB(FrizerieWebClient.FrizerieRef.AdaugaInDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdaugaInDB", ReplyAction="*")]
        System.Threading.Tasks.Task<FrizerieWebClient.FrizerieRef.AdaugaInDBResponse> AdaugaInDBAsync(FrizerieWebClient.FrizerieRef.AdaugaInDBRequest request);
        
        // CODEGEN: Generating message contract since element name client from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificaProgramare", ReplyAction="*")]
        FrizerieWebClient.FrizerieRef.ModificaProgramareResponse ModificaProgramare(FrizerieWebClient.FrizerieRef.ModificaProgramareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificaProgramare", ReplyAction="*")]
        System.Threading.Tasks.Task<FrizerieWebClient.FrizerieRef.ModificaProgramareResponse> ModificaProgramareAsync(FrizerieWebClient.FrizerieRef.ModificaProgramareRequest request);
        
        // CODEGEN: Generating message contract since element name StergeProgramareResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergeProgramare", ReplyAction="*")]
        FrizerieWebClient.FrizerieRef.StergeProgramareResponse StergeProgramare(FrizerieWebClient.FrizerieRef.StergeProgramareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StergeProgramare", ReplyAction="*")]
        System.Threading.Tasks.Task<FrizerieWebClient.FrizerieRef.StergeProgramareResponse> StergeProgramareAsync(FrizerieWebClient.FrizerieRef.StergeProgramareRequest request);
        
        // CODEGEN: Generating message contract since element name GetToateProgramarileResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetToateProgramarile", ReplyAction="*")]
        FrizerieWebClient.FrizerieRef.GetToateProgramarileResponse GetToateProgramarile(FrizerieWebClient.FrizerieRef.GetToateProgramarileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetToateProgramarile", ReplyAction="*")]
        System.Threading.Tasks.Task<FrizerieWebClient.FrizerieRef.GetToateProgramarileResponse> GetToateProgramarileAsync(FrizerieWebClient.FrizerieRef.GetToateProgramarileRequest request);
        
        // CODEGEN: Generating message contract since element name FiltreazaDupaDataResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FiltreazaDupaData", ReplyAction="*")]
        FrizerieWebClient.FrizerieRef.FiltreazaDupaDataResponse FiltreazaDupaData(FrizerieWebClient.FrizerieRef.FiltreazaDupaDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FiltreazaDupaData", ReplyAction="*")]
        System.Threading.Tasks.Task<FrizerieWebClient.FrizerieRef.FiltreazaDupaDataResponse> FiltreazaDupaDataAsync(FrizerieWebClient.FrizerieRef.FiltreazaDupaDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugaInDBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugaInDB", Namespace="http://tempuri.org/", Order=0)]
        public FrizerieWebClient.FrizerieRef.AdaugaInDBRequestBody Body;
        
        public AdaugaInDBRequest() {
        }
        
        public AdaugaInDBRequest(FrizerieWebClient.FrizerieRef.AdaugaInDBRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdaugaInDBRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string client;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tip;
        
        public AdaugaInDBRequestBody() {
        }
        
        public AdaugaInDBRequestBody(string client, System.DateTime data, string tip) {
            this.client = client;
            this.data = data;
            this.tip = tip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdaugaInDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdaugaInDBResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrizerieWebClient.FrizerieRef.AdaugaInDBResponseBody Body;
        
        public AdaugaInDBResponse() {
        }
        
        public AdaugaInDBResponse(FrizerieWebClient.FrizerieRef.AdaugaInDBResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdaugaInDBResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AdaugaInDBResult;
        
        public AdaugaInDBResponseBody() {
        }
        
        public AdaugaInDBResponseBody(string AdaugaInDBResult) {
            this.AdaugaInDBResult = AdaugaInDBResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificaProgramareRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificaProgramare", Namespace="http://tempuri.org/", Order=0)]
        public FrizerieWebClient.FrizerieRef.ModificaProgramareRequestBody Body;
        
        public ModificaProgramareRequest() {
        }
        
        public ModificaProgramareRequest(FrizerieWebClient.FrizerieRef.ModificaProgramareRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificaProgramareRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string client;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tip;
        
        public ModificaProgramareRequestBody() {
        }
        
        public ModificaProgramareRequestBody(int id, string client, System.DateTime data, string tip) {
            this.id = id;
            this.client = client;
            this.data = data;
            this.tip = tip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificaProgramareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificaProgramareResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrizerieWebClient.FrizerieRef.ModificaProgramareResponseBody Body;
        
        public ModificaProgramareResponse() {
        }
        
        public ModificaProgramareResponse(FrizerieWebClient.FrizerieRef.ModificaProgramareResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificaProgramareResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ModificaProgramareResult;
        
        public ModificaProgramareResponseBody() {
        }
        
        public ModificaProgramareResponseBody(string ModificaProgramareResult) {
            this.ModificaProgramareResult = ModificaProgramareResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StergeProgramareRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StergeProgramare", Namespace="http://tempuri.org/", Order=0)]
        public FrizerieWebClient.FrizerieRef.StergeProgramareRequestBody Body;
        
        public StergeProgramareRequest() {
        }
        
        public StergeProgramareRequest(FrizerieWebClient.FrizerieRef.StergeProgramareRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StergeProgramareRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public StergeProgramareRequestBody() {
        }
        
        public StergeProgramareRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StergeProgramareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StergeProgramareResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrizerieWebClient.FrizerieRef.StergeProgramareResponseBody Body;
        
        public StergeProgramareResponse() {
        }
        
        public StergeProgramareResponse(FrizerieWebClient.FrizerieRef.StergeProgramareResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StergeProgramareResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StergeProgramareResult;
        
        public StergeProgramareResponseBody() {
        }
        
        public StergeProgramareResponseBody(string StergeProgramareResult) {
            this.StergeProgramareResult = StergeProgramareResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetToateProgramarileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToateProgramarile", Namespace="http://tempuri.org/", Order=0)]
        public FrizerieWebClient.FrizerieRef.GetToateProgramarileRequestBody Body;
        
        public GetToateProgramarileRequest() {
        }
        
        public GetToateProgramarileRequest(FrizerieWebClient.FrizerieRef.GetToateProgramarileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetToateProgramarileRequestBody {
        
        public GetToateProgramarileRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetToateProgramarileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToateProgramarileResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrizerieWebClient.FrizerieRef.GetToateProgramarileResponseBody Body;
        
        public GetToateProgramarileResponse() {
        }
        
        public GetToateProgramarileResponse(FrizerieWebClient.FrizerieRef.GetToateProgramarileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetToateProgramarileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrizerieWebClient.FrizerieRef.ModelProgramare[] GetToateProgramarileResult;
        
        public GetToateProgramarileResponseBody() {
        }
        
        public GetToateProgramarileResponseBody(FrizerieWebClient.FrizerieRef.ModelProgramare[] GetToateProgramarileResult) {
            this.GetToateProgramarileResult = GetToateProgramarileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FiltreazaDupaDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FiltreazaDupaData", Namespace="http://tempuri.org/", Order=0)]
        public FrizerieWebClient.FrizerieRef.FiltreazaDupaDataRequestBody Body;
        
        public FiltreazaDupaDataRequest() {
        }
        
        public FiltreazaDupaDataRequest(FrizerieWebClient.FrizerieRef.FiltreazaDupaDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FiltreazaDupaDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime dataCautata;
        
        public FiltreazaDupaDataRequestBody() {
        }
        
        public FiltreazaDupaDataRequestBody(System.DateTime dataCautata) {
            this.dataCautata = dataCautata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FiltreazaDupaDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FiltreazaDupaDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public FrizerieWebClient.FrizerieRef.FiltreazaDupaDataResponseBody Body;
        
        public FiltreazaDupaDataResponse() {
        }
        
        public FiltreazaDupaDataResponse(FrizerieWebClient.FrizerieRef.FiltreazaDupaDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FiltreazaDupaDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FrizerieWebClient.FrizerieRef.ModelProgramare[] FiltreazaDupaDataResult;
        
        public FiltreazaDupaDataResponseBody() {
        }
        
        public FiltreazaDupaDataResponseBody(FrizerieWebClient.FrizerieRef.ModelProgramare[] FiltreazaDupaDataResult) {
            this.FiltreazaDupaDataResult = FiltreazaDupaDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProgramariServiceSoapChannel : FrizerieWebClient.FrizerieRef.ProgramariServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProgramariServiceSoapClient : System.ServiceModel.ClientBase<FrizerieWebClient.FrizerieRef.ProgramariServiceSoap>, FrizerieWebClient.FrizerieRef.ProgramariServiceSoap {
        
        public ProgramariServiceSoapClient() {
        }
        
        public ProgramariServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProgramariServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProgramariServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProgramariServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrizerieWebClient.FrizerieRef.AdaugaInDBResponse FrizerieWebClient.FrizerieRef.ProgramariServiceSoap.AdaugaInDB(FrizerieWebClient.FrizerieRef.AdaugaInDBRequest request) {
            return base.Channel.AdaugaInDB(request);
        }
        
        public string AdaugaInDB(string client, System.DateTime data, string tip) {
            FrizerieWebClient.FrizerieRef.AdaugaInDBRequest inValue = new FrizerieWebClient.FrizerieRef.AdaugaInDBRequest();
            inValue.Body = new FrizerieWebClient.FrizerieRef.AdaugaInDBRequestBody();
            inValue.Body.client = client;
            inValue.Body.data = data;
            inValue.Body.tip = tip;
            FrizerieWebClient.FrizerieRef.AdaugaInDBResponse retVal = ((FrizerieWebClient.FrizerieRef.ProgramariServiceSoap)(this)).AdaugaInDB(inValue);
            return retVal.Body.AdaugaInDBResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrizerieWebClient.FrizerieRef.AdaugaInDBResponse> FrizerieWebClient.FrizerieRef.ProgramariServiceSoap.AdaugaInDBAsync(FrizerieWebClient.FrizerieRef.AdaugaInDBRequest request) {
            return base.Channel.AdaugaInDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrizerieWebClient.FrizerieRef.AdaugaInDBResponse> AdaugaInDBAsync(string client, System.DateTime data, string tip) {
            FrizerieWebClient.FrizerieRef.AdaugaInDBRequest inValue = new FrizerieWebClient.FrizerieRef.AdaugaInDBRequest();
            inValue.Body = new FrizerieWebClient.FrizerieRef.AdaugaInDBRequestBody();
            inValue.Body.client = client;
            inValue.Body.data = data;
            inValue.Body.tip = tip;
            return ((FrizerieWebClient.FrizerieRef.ProgramariServiceSoap)(this)).AdaugaInDBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrizerieWebClient.FrizerieRef.ModificaProgramareResponse FrizerieWebClient.FrizerieRef.ProgramariServiceSoap.ModificaProgramare(FrizerieWebClient.FrizerieRef.ModificaProgramareRequest request) {
            return base.Channel.ModificaProgramare(request);
        }
        
        public string ModificaProgramare(int id, string client, System.DateTime data, string tip) {
            FrizerieWebClient.FrizerieRef.ModificaProgramareRequest inValue = new FrizerieWebClient.FrizerieRef.ModificaProgramareRequest();
            inValue.Body = new FrizerieWebClient.FrizerieRef.ModificaProgramareRequestBody();
            inValue.Body.id = id;
            inValue.Body.client = client;
            inValue.Body.data = data;
            inValue.Body.tip = tip;
            FrizerieWebClient.FrizerieRef.ModificaProgramareResponse retVal = ((FrizerieWebClient.FrizerieRef.ProgramariServiceSoap)(this)).ModificaProgramare(inValue);
            return retVal.Body.ModificaProgramareResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrizerieWebClient.FrizerieRef.ModificaProgramareResponse> FrizerieWebClient.FrizerieRef.ProgramariServiceSoap.ModificaProgramareAsync(FrizerieWebClient.FrizerieRef.ModificaProgramareRequest request) {
            return base.Channel.ModificaProgramareAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrizerieWebClient.FrizerieRef.ModificaProgramareResponse> ModificaProgramareAsync(int id, string client, System.DateTime data, string tip) {
            FrizerieWebClient.FrizerieRef.ModificaProgramareRequest inValue = new FrizerieWebClient.FrizerieRef.ModificaProgramareRequest();
            inValue.Body = new FrizerieWebClient.FrizerieRef.ModificaProgramareRequestBody();
            inValue.Body.id = id;
            inValue.Body.client = client;
            inValue.Body.data = data;
            inValue.Body.tip = tip;
            return ((FrizerieWebClient.FrizerieRef.ProgramariServiceSoap)(this)).ModificaProgramareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrizerieWebClient.FrizerieRef.StergeProgramareResponse FrizerieWebClient.FrizerieRef.ProgramariServiceSoap.StergeProgramare(FrizerieWebClient.FrizerieRef.StergeProgramareRequest request) {
            return base.Channel.StergeProgramare(request);
        }
        
        public string StergeProgramare(int id) {
            FrizerieWebClient.FrizerieRef.StergeProgramareRequest inValue = new FrizerieWebClient.FrizerieRef.StergeProgramareRequest();
            inValue.Body = new FrizerieWebClient.FrizerieRef.StergeProgramareRequestBody();
            inValue.Body.id = id;
            FrizerieWebClient.FrizerieRef.StergeProgramareResponse retVal = ((FrizerieWebClient.FrizerieRef.ProgramariServiceSoap)(this)).StergeProgramare(inValue);
            return retVal.Body.StergeProgramareResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrizerieWebClient.FrizerieRef.StergeProgramareResponse> FrizerieWebClient.FrizerieRef.ProgramariServiceSoap.StergeProgramareAsync(FrizerieWebClient.FrizerieRef.StergeProgramareRequest request) {
            return base.Channel.StergeProgramareAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrizerieWebClient.FrizerieRef.StergeProgramareResponse> StergeProgramareAsync(int id) {
            FrizerieWebClient.FrizerieRef.StergeProgramareRequest inValue = new FrizerieWebClient.FrizerieRef.StergeProgramareRequest();
            inValue.Body = new FrizerieWebClient.FrizerieRef.StergeProgramareRequestBody();
            inValue.Body.id = id;
            return ((FrizerieWebClient.FrizerieRef.ProgramariServiceSoap)(this)).StergeProgramareAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrizerieWebClient.FrizerieRef.GetToateProgramarileResponse FrizerieWebClient.FrizerieRef.ProgramariServiceSoap.GetToateProgramarile(FrizerieWebClient.FrizerieRef.GetToateProgramarileRequest request) {
            return base.Channel.GetToateProgramarile(request);
        }
        
        public FrizerieWebClient.FrizerieRef.ModelProgramare[] GetToateProgramarile() {
            FrizerieWebClient.FrizerieRef.GetToateProgramarileRequest inValue = new FrizerieWebClient.FrizerieRef.GetToateProgramarileRequest();
            inValue.Body = new FrizerieWebClient.FrizerieRef.GetToateProgramarileRequestBody();
            FrizerieWebClient.FrizerieRef.GetToateProgramarileResponse retVal = ((FrizerieWebClient.FrizerieRef.ProgramariServiceSoap)(this)).GetToateProgramarile(inValue);
            return retVal.Body.GetToateProgramarileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrizerieWebClient.FrizerieRef.GetToateProgramarileResponse> FrizerieWebClient.FrizerieRef.ProgramariServiceSoap.GetToateProgramarileAsync(FrizerieWebClient.FrizerieRef.GetToateProgramarileRequest request) {
            return base.Channel.GetToateProgramarileAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrizerieWebClient.FrizerieRef.GetToateProgramarileResponse> GetToateProgramarileAsync() {
            FrizerieWebClient.FrizerieRef.GetToateProgramarileRequest inValue = new FrizerieWebClient.FrizerieRef.GetToateProgramarileRequest();
            inValue.Body = new FrizerieWebClient.FrizerieRef.GetToateProgramarileRequestBody();
            return ((FrizerieWebClient.FrizerieRef.ProgramariServiceSoap)(this)).GetToateProgramarileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FrizerieWebClient.FrizerieRef.FiltreazaDupaDataResponse FrizerieWebClient.FrizerieRef.ProgramariServiceSoap.FiltreazaDupaData(FrizerieWebClient.FrizerieRef.FiltreazaDupaDataRequest request) {
            return base.Channel.FiltreazaDupaData(request);
        }
        
        public FrizerieWebClient.FrizerieRef.ModelProgramare[] FiltreazaDupaData(System.DateTime dataCautata) {
            FrizerieWebClient.FrizerieRef.FiltreazaDupaDataRequest inValue = new FrizerieWebClient.FrizerieRef.FiltreazaDupaDataRequest();
            inValue.Body = new FrizerieWebClient.FrizerieRef.FiltreazaDupaDataRequestBody();
            inValue.Body.dataCautata = dataCautata;
            FrizerieWebClient.FrizerieRef.FiltreazaDupaDataResponse retVal = ((FrizerieWebClient.FrizerieRef.ProgramariServiceSoap)(this)).FiltreazaDupaData(inValue);
            return retVal.Body.FiltreazaDupaDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FrizerieWebClient.FrizerieRef.FiltreazaDupaDataResponse> FrizerieWebClient.FrizerieRef.ProgramariServiceSoap.FiltreazaDupaDataAsync(FrizerieWebClient.FrizerieRef.FiltreazaDupaDataRequest request) {
            return base.Channel.FiltreazaDupaDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<FrizerieWebClient.FrizerieRef.FiltreazaDupaDataResponse> FiltreazaDupaDataAsync(System.DateTime dataCautata) {
            FrizerieWebClient.FrizerieRef.FiltreazaDupaDataRequest inValue = new FrizerieWebClient.FrizerieRef.FiltreazaDupaDataRequest();
            inValue.Body = new FrizerieWebClient.FrizerieRef.FiltreazaDupaDataRequestBody();
            inValue.Body.dataCautata = dataCautata;
            return ((FrizerieWebClient.FrizerieRef.ProgramariServiceSoap)(this)).FiltreazaDupaDataAsync(inValue);
        }
    }
}
